{
 "title": "Loki Operations & Security",
 "tags": [
  "loki",
  "security",
  "operations"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPS 5min",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate({container_name=\"app\"} |= `request` [5m])"
    }
   ]
  },
  {
   "title": "p95 processing time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile_over_time(\r\n  0.95,\r\n  {event=\"log\", container_name=\"app\"}\r\n  | json text=\"message.event\", processing_time=\"message.processing_time\"\r\n  | text = \"request\"\r\n  | unwrap processing_time [15m]\r\n)"
    }
   ]
  },
  {
   "title": "p99 processing time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile_over_time(\r\n  0.99,\r\n  {event=\"log\", container_name=\"app\"}\r\n  | json text=\"message.event\", processing_time=\"message.processing_time\"\r\n  | text = \"request\"\r\n  | unwrap processing_time [15m]\r\n)"
    }
   ]
  },
  { "title": "logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Exception",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "{container_name=\"app\", event=\"log\"} | json level=`message.level`, detail=\"message.detail\", request_id=\"message.request_id\", code=\"message.code\", title=\"message.title\" | unpack"
    }
   ]
  },
  {
   "title": "Top failing endpoints (1h)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(\r\n  10,\r\n  sum by (path, status_code) (\r\n    count_over_time(\r\n      {event=\"log\", container_name=\"app\"}\r\n      | json path=\"message.path\", status_code=\"message.status_code\", text=\"message.event\"\r\n      | text = \"request\"\r\n      | status_code =~ \"4..|5..\"\r\n      [15m]\r\n    )\r\n  )\r\n)"
    }
   ]
  },
  { "title": "Metric", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Registrations (24h)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container_name=\"app\"} | json | unpack | message_event = `Register user` [24h]))"
    }
   ]
  },
  {
   "title": "Login (24h)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container_name=\"app\"} |= `/auth/login` [24h]))",
     "legendFormat": "Login"
    },
    {
     "expr": "sum(count_over_time({container_name=\"app\"} |= `/auth/login` | json status = `message.status_code` | status =~ `4..|5..` [24h]))",
     "legendFormat": "Failied login"
    }
   ]
  }
 ]
}