"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { ArrowRight, BarChart3, Loader2 } from "lucide-react";
import { apiRequest, ApiError, setAccessToken } from "@/utils/api/client";

export default function SignIn() {
  const router = useRouter(); const [error, setError] = useState(""); const [pending, setPending] = useState(false);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(""); setPending(true); const form = new FormData(event.currentTarget); try { const response = await fetch("/api/auth/login", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ username: String(form.get("email") ?? ""), password: String(form.get("password") ?? "") }) }); const result = await response.json(); if (!response.ok) throw new ApiError(result.error?.message ?? "Не удалось войти", response.status, result.error?.code); setAccessToken(result.access_token); router.replace(new URLSearchParams(window.location.search).get("next") || "/dashboard"); } catch (value) { setError(value instanceof ApiError ? value.message : "Не удалось войти"); } finally { setPending(false); } };
  return <section className="grid min-h-screen lg:grid-cols-[1.1fr_.9fr]"><div className="hidden bg-[#18362c] p-12 text-white lg:flex lg:flex-col lg:justify-between"><div className="flex items-center gap-3 font-semibold"><span className="grid size-9 place-items-center rounded-md bg-[#c7f36b] text-[#18362c]"><BarChart3 size={19} /></span>Оцифровка</div><div className="max-w-xl"><p className="mb-5 text-xs font-semibold uppercase tracking-[.16em] text-[#c7f36b]">Внутренняя аналитика</p><h1 className="font-nacelle text-4xl font-semibold leading-tight">Продажи, прибыль и остатки — в одном рабочем контуре.</h1><p className="mt-5 max-w-lg text-base leading-7 text-white/65">Доступ к данным Wildberries, Ozon и Яндекс Маркета только для сотрудников.</p></div><p className="text-xs text-white/40">Доступ контролируется backend.</p></div><div className="flex items-center justify-center px-5 py-12"><form onSubmit={submit} className="w-full max-w-sm rounded-lg border border-[#dfe2dc] bg-white p-7 shadow-sm"><div className="mb-7 lg:hidden"><span className="inline-flex items-center gap-2 font-semibold"><BarChart3 size={20} className="text-[#34745f]" />Оцифровка</span></div><h2 className="text-2xl font-semibold">Вход в кабинет</h2><p className="mt-2 text-[#6d726c]">Используйте рабочую учётную запись.</p><div className="mt-7 space-y-5"><label className="block text-sm font-medium" htmlFor="email">Email<input id="email" name="email" type="email" autoComplete="email" required className="form-input mt-2 w-full" placeholder="name@company.ru" /></label><label className="block text-sm font-medium" htmlFor="password">Пароль<input id="password" name="password" type="password" autoComplete="current-password" required className="form-input mt-2 w-full" placeholder="••••••••" /></label></div>{error && <p className="mt-4 rounded-md border border-[#edcfc7] bg-[#fff3f0] p-2.5 text-xs text-[#a54b31]" role="alert">{error}</p>}<div className="mt-3 text-right"><Link className="text-xs font-medium text-[#34745f] hover:underline" href="/reset-password">Восстановить пароль</Link></div><button disabled={pending} className="mt-6 inline-flex w-full items-center justify-center gap-2 rounded-md bg-[#18362c] px-4 py-3 font-medium text-white transition hover:bg-[#24503f]">{pending && <Loader2 size={17} className="animate-spin" />}Войти {!pending && <ArrowRight size={17} />}</button><p className="mt-5 text-center text-xs text-[#858b84]">Регистрация закрыта. Обратитесь к владельцу организации.</p></form></div></section>;
}
